<!-- Ce code CSS n'est chargé que depuis la page connexion -->
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/utilForm.css">
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/formConnect.css">


<div>
   <?php if(isset($errorConnect)){ ?> <!-- Si la variable $flashBag contient un message -->
   <h2 style="color: red;"><?= $errorConnect->fetchMessage() ?></h2>
   <?php }; ?><!--  On affiche le message  -->
</div>

<div style="background-color: #999999;">
   <div class="limiter">
      <div class="container-login100" style="background-image: url('<?= $wwwUrl ?>/images/watchConnect.jpg');">
         <div class="wrap-login100 p-t-30 p-b-50">
            <span class="login100-form-title p-b-41">
            Connexion
            </span>
            <form action="./connexion" method="post" class="login100-form validate-form p-b-33 p-t-5">
               <div class="wrap-input100 validate-input" data-validate = "Enter username">
                  <input class="input100" type="text" name="email" placeholder="Email">
                  <span class="focus-input100"></span>
               </div>
               <div class="wrap-input100 validate-input" data-validate="Enter password">
                  <input class="input100" type="password" name="password" placeholder="Mot de passe">
                  <span class="focus-input100"></span>
               </div>
               <div class="container-login100-form-btn ">
                  <button class="login100-form-btn ">
                  Login
                  </button>
                  <a href="<?= $requestUrl ?>/user/register" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
                  S'enregistrer
                  <i class="fa fa-long-arrow-right m-l-5"></i>
                  </a>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
