<!-- Ce code CSS n'est chargé que depuis la page contact -->
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/utilForm.css">
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/formContact.css">


<div>
   <?php if(isset($validMessage)){ ?> <!-- Si la variable contient un message -->
   <h2 class="validMessage"><?= $validMessage->fetchMessage() ?></h2><!-- On affiche le message -->
   <?php }; ?>
   <?php if(isset($errorContact)){ ?> 
   <h2 class="errorContact"><?= $errorContact->fetchMessage() ?></h2>
   <?php }; ?>
</div>

<div class="mainContact">
   <div class="limiter">
      <div class="container-login100">
         <div class="login100-more"></div>
         <div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">
            <form action="<?= $requestUrl ?>/contact" method="post" class="login100-form validate-form">
               <span class="login100-form-title p-b-59">
               Nous contacter
               </span>
               <div class="wrap-input100 validate-input">
                  <span class="label-input100">Nom</span>
                  <input class="input100" type="text" name="lastName" minlength="2" maxlength="40" placeholder="Nom" required>
                  <span class="focus-input100"></span>
               </div>
               <div class="wrap-input100 validate-input">
                  <span class="label-input100">Email</span>
                  <input class="input100" type="text" name="email" maxlength="50" placeholder="Email@example.com" required>
                  <span class="focus-input100"></span>
               </div>
               <div class="wrap-input100 validate-input" >
                  <label class="label-input100" for="message">Message</label>
                  <textarea rows="10" cols="30" type="text" class="input100" name="message" maxlength="255" placeholder="Votre message..." required></textarea>
                  <span class="focus-input100"></span>
               </div>
               <div class="container-login100-form-btn">
                  <div class="wrap-login100-form-btn">
                     <div class="login100-form-bgbtn"></div>
                     <button type="submit" class="login100-form-btn">
                     Envoyer
                     </button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3306.0263458493882!2d-118.26951788663767!3d34.043195282448174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c7b85dea2a93%3A0x1ff47c3ceb7bb2d5!2sStaples%20Center!5e0!3m2!1sfr!2sfr!4v1571855075546!5m2!1sfr!2sfr" width="100%" height="450" frameborder="0" allowfullscreen=""></iframe>
</div>
